const pages={index:'index.html',projects:'projects.html',gallery:'gallery.html',services:'services.html',about:'about.html',contact:'contact.html'};
const navItems=[['index','Home','الرئيسية'],['projects','Projects','المشاريع'],['gallery','Gallery','معرض الأعمال'],['services','Services','الخدمات'],['about','About','عن المكتب'],['contact','Contact','تواصل']];
function getTheme(){return localStorage.getItem('me-theme')||'dark'}
function logoForTheme(){return getTheme()==='dark'?'LOGO WIHT.png':'LOGO BALCK.png'}
function injectLoader(){document.body.insertAdjacentHTML('afterbegin',`<div class="site-loader"><img class="loader-logo theme-logo" src="${logoForTheme()}" alt="M. Elgamal Office logo"></div>`);const loader=document.querySelector('.site-loader');window.addEventListener('load',()=>{setTimeout(()=>{loader?.classList.add('is-hidden');setTimeout(()=>loader?.remove(),300)},400)})}
function injectNav(){const current=document.body.dataset.page||'index';document.body.insertAdjacentHTML('afterbegin',`<header class="site-header"><a class="brand" href="index.html"><img class="theme-logo" src="${logoForTheme()}" alt="M. Elgamal Office"><span class="brand-name" data-en="M. Elgamal Office" data-ar="مكتب م. الجمال"></span></a><nav class="nav-links" id="navLinks">${navItems.map(([id,en,ar])=>`<a href="${pages[id]}" class="${current===id?'active':''}" data-en="${en}" data-ar="${ar}"></a>`).join('')}</nav><div class="nav-actions"><button class="icon-btn lang-toggle" type="button" aria-label="Toggle language">AR</button><button class="icon-btn theme-toggle" id="theme-toggle" type="button" aria-label="Toggle dark mode"><svg class="icon-sun" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"></circle><line x1="12" y1="2" x2="12" y2="4"></line><line x1="12" y1="20" x2="12" y2="22"></line><line x1="4.93" y1="4.93" x2="6.34" y2="6.34"></line><line x1="17.66" y1="17.66" x2="19.07" y2="19.07"></line><line x1="2" y1="12" x2="4" y2="12"></line><line x1="20" y1="12" x2="22" y2="12"></line><line x1="4.93" y1="19.07" x2="6.34" y2="17.66"></line><line x1="17.66" y1="6.34" x2="19.07" y2="4.93"></line></svg><svg class="icon-moon" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path></svg></button><button class="icon-btn hamburger" type="button" aria-label="Menu">☰</button></div></header>`)}
function injectFooter(){document.body.insertAdjacentHTML('beforeend',`<footer class="site-footer"><div class="footer-grid"><div><img class="footer-logo theme-logo" src="${logoForTheme()}" alt="M. Elgamal Office"><h3 data-en="M. Elgamal Office" data-ar="مكتب م. الجمال"></h3><p data-en="Architecture and interior design office serving Cairo, Sadat City, and Monufia." data-ar="مكتب عمارة وتصميم داخلي يخدم القاهرة ومدينة السادات والمنوفية."></p></div><div class="footer-links">${navItems.map(([id,en,ar])=>`<a href="${pages[id]}" data-en="${en}" data-ar="${ar}"></a>`).join('')}</div><div class="social-links"><a href="https://www.instagram.com/ashraf_architect" target="_blank">Instagram</a><a href="https://www.facebook.com/share/1CDEyMN25B/" target="_blank">Facebook</a><a href="https://www.linkedin.com/in/mohammed-el-gamal-34937b297" target="_blank">LinkedIn</a><a href="https://wa.me/201555811088" target="_blank">01555811088</a><a href="mailto:ma7med2shraf001@gmail.com">ma7med2shraf001@gmail.com</a><p data-en="© 2025 M. Elgamal Office. All rights reserved." data-ar="© 2025 مكتب م. الجمال. جميع الحقوق محفوظة."></p></div></div></footer>`)}
function applyLang(lang){document.documentElement.lang=lang==='ar'?'ar':'en';document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-en][data-ar]').forEach(el=>{el.textContent=el.dataset[lang]});document.querySelectorAll('[data-placeholder-en]').forEach(el=>{el.placeholder=lang==='ar'?el.dataset.placeholderAr:el.dataset.placeholderEn});document.querySelectorAll('.lang-toggle').forEach(btn=>btn.textContent=lang==='ar'?'EN':'AR');localStorage.setItem('me-lang',lang)}
function initLang(){applyLang(localStorage.getItem('me-lang')||'en');document.querySelectorAll('.lang-toggle').forEach(btn=>btn.addEventListener('click',()=>applyLang((localStorage.getItem('me-lang')||'en')==='en'?'ar':'en')))}
function applyTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('me-theme',theme);document.querySelectorAll('.theme-logo').forEach(img=>img.src=logoForTheme())}
function initTheme(){applyTheme(getTheme());document.querySelectorAll('.theme-toggle').forEach(btn=>btn.addEventListener('click',()=>applyTheme(getTheme()==='dark'?'light':'dark')))}
function initReveal(){const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>obs.observe(el))}
function initCursor(){if(matchMedia('(pointer:fine)').matches){const dot=document.createElement('div');dot.className='cursor-dot';document.body.appendChild(dot);window.addEventListener('mousemove',e=>{dot.style.left=e.clientX+'px';dot.style.top=e.clientY+'px'})}}
function initPageTransitions(){document.querySelectorAll('a[href$=".html"]').forEach(a=>a.addEventListener('click',e=>{if(a.target)return;e.preventDefault();document.body.classList.add('page-transitioning');setTimeout(()=>location.href=a.href,180)}))}
function initLightbox(){const box=document.createElement('div');box.className='lightbox';box.innerHTML='<button class="lightbox-close" aria-label="Close">×</button><img alt="Gallery image">';document.body.appendChild(box);const img=box.querySelector('img');document.querySelectorAll('[data-lightbox] img,.gallery-item img').forEach(el=>el.addEventListener('click',()=>{img.src=el.src;box.classList.add('open')}));box.addEventListener('click',e=>{if(e.target===box||e.target.classList.contains('lightbox-close'))box.classList.remove('open')})}
function initFilters(){document.querySelectorAll('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;document.querySelectorAll('[data-category]').forEach(item=>{item.style.display=(f==='all'||item.dataset.category.split(' ').includes(f))?'block':'none'})}))}
function initContact(){const form=document.querySelector('.contact-form');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();form.reset();document.querySelector('.form-success').style.display='block'})}
function initMobileNav(){document.querySelector('.hamburger')?.addEventListener('click',()=>document.querySelector('.nav-links')?.classList.toggle('open'))}
function initBlueprints(){document.querySelectorAll('.needs-blueprint').forEach(el=>el.insertAdjacentHTML('afterbegin','<div class="blueprint-canvas"></div>'))}
document.addEventListener('DOMContentLoaded',()=>{injectLoader();injectNav();injectFooter();initTheme();initLang();initBlueprints();initReveal();initCursor();initPageTransitions();initLightbox();initFilters();initContact();initMobileNav()});


